site_name: Visivo Docs

plugins:
  - search: {}
  - macros
  - spellcheck:
      backends:  # the backends you want to use
        - symspellpy  # as strings
        - codespell:  # or nested configs
            dictionaries: [clear, rare]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/visivo-io/visivo
repo_name: visivo-io/visivo
theme:
  custom_dir: mkdocs/overrides
  name: material
  features:
    - content.tabs.link
    - navigation.sections
  logo: assets/favicon_io/android-chrome-192x192.png
  favicon: assets/favicon_io/favicon-32x32.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: visivo_light 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: visivo_dark 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: 'mkdocs'
site_dir: 'mkdocs_build'

extra:
  analytics:
    provider: google
    property: G-50DF3C95TL

extra_css:
  - stylesheets/brand_colors.css

nav:
  - Getting Started: index.md
    # - Use Cases: use_cases.md
    # - Tutorials: how_tos.md
  - Reference: 
      - CLI: cli-reference.md
      - Configuration: 
        - model-docs/trace.md
        - model-docs/chart.md
        - model-docs/target.md
        - model-docs/dashboard.md
        - model-docs/default.md
        - model-docs/alert.md
  - Background:
    - Viewpoint: viewpoint.md
    - How It Works: how_it_works.md

