site_name: Visivo

plugins:
  - search: {}
  - encryptcontent:
      search_index: 'clear'
      global_password: 'secrets'
      title_prefix: ''
      summary: '<p class="--md-accent-fg-color">We are carefully rolling out our product.  Interested in learning more? Contact us at <a href="mailto:join@visivo.io" class="text-highlight">join@visivo.io</a></p>'
      placeholder: 'Input Password Here'
      encryption_info_message: 'Password'
      remember_password: True
      default_expire_delay: 72

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  features:
    - content.tabs.link
  logo: assets/favicon_io/android-chrome-192x192.png
  favicon: assets/favicon_io/favicon-32x32.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: 'mkdocs'
site_dir: 'mkdocs_build'

extra_css:
  - stylesheets/brand_colors.css

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Use Cases: use_cases.md
  - Tutorials: how_tos.md
  - How It Works: how_it_works.md
  - CLI Referrence: referrence.md
