site_name: Visivo Docs

plugins:
  - search: {}
  - macros
  - spellcheck:
      backends: # the backends you want to use
        - symspellpy # as strings
        - codespell: # or nested configs
            dictionaries: [clear, rare]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/visivo-io/visivo
repo_name: visivo-io/visivo
theme:
  name: material
  features:
    - content.tabs.link
    #- navigation.tabs
    - navigation.indexes
    #- navigation.path
    - navigation.sections
    - content.tooltips
  logo: assets/favicon_io/android-chrome-192x192.png
  favicon: assets/favicon_io/favicon-32x32.png
  icon:
    annotation: material/arrow-right-circle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: visivo_light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: visivo_dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: "mkdocs"
site_dir: "mkdocs_build"

extra:
  analytics:
    provider: google
    property: G-50DF3C95TL

extra_css:
  - stylesheets/brand_colors.css

nav:
  - Getting Started: index.md
  - Topics:
      - Linting: topics/linting.md
      - Including: topics/including.md
      - Deployment: topics/deployments.md
    # - Use Cases: use_cases.md
    # - Tutorials: how_tos.md
  - Reference:
      - CLI: cli-reference.md
      - Configuration:
          - Traces: 
            - model-docs/traces/index.md
          #- Trace Properties:
            - '<b>Bar</b>': model-docs/traces/bar.md
            - BarPolar: model-docs/traces/barpolar.md
            - '<b>Box</b>': model-docs/traces/box.md
            - CandleStick: model-docs/traces/candlestick.md
            - Carpet: model-docs/traces/carpet.md
            - Choropleth: model-docs/traces/choropleth.md
            - ChoroplethMapBox: model-docs/traces/choroplethmapbox.md
            - Cone: model-docs/traces/cone.md
            - Contour: model-docs/traces/contour.md
            - ContourCarpet: model-docs/traces/contourcarpet.md
            - DensityMapBox: model-docs/traces/densitymapbox.md
            - '<b>Funnel</b>': model-docs/traces/funnel.md
            - FunnelArea: model-docs/traces/funnelarea.md
            - Heatmap: model-docs/traces/heatmap.md
            - Heatmapgl: model-docs/traces/heatmapgl.md
            - Histogram: model-docs/traces/histogram.md
            - Histogram2d: model-docs/traces/histogram2d.md
            - Histogram2dContour: model-docs/traces/histogram2dcontour.md
            - Icicle: model-docs/traces/icicle.md
            - Image: model-docs/traces/image.md
            - Indicator: model-docs/traces/indicator.md
            - IsoSurface: model-docs/traces/isosurface.md
            - Mesh3d: model-docs/traces/mesh3d.md
            - Ohlc: model-docs/traces/ohlc.md
            - Parcats: model-docs/traces/parcats.md
            - Parcoords: model-docs/traces/parcoords.md
            - '<b>Pie</b>': model-docs/traces/pie.md
            - Sankey: model-docs/traces/sankey.md
            - '<b>Scatter</b>': model-docs/traces/scatter.md
            - Scatter3d: model-docs/traces/scatter3d.md
            - ScatterCarpet: model-docs/traces/scattercarpet.md
            - ScatterGeo: model-docs/traces/scattergeo.md
            - ScatterGL: model-docs/traces/scattergl.md
            - ScatterMapBox: model-docs/traces/scattermapbox.md
            - ScatterPolar: model-docs/traces/scatterpolar.md
            - ScatterPolarGl: model-docs/traces/scatterpolargl.md
            - ScatterSmith: model-docs/traces/scattersmith.md
            - Scatterternary: model-docs/traces/scatterternary.md
            - Splom: model-docs/traces/splom.md
            - Streamtube: model-docs/traces/streamtube.md
            - Sunburst: model-docs/traces/sunburst.md
            - Surface: model-docs/traces/surface.md
            - '<b>Treemap</b>': model-docs/traces/treemap.md
            - Violin: model-docs/traces/violin.md
            - Volume: model-docs/traces/volume.md
            - '<b>Waterfall</b>': model-docs/traces/waterfall.md
          - Charts: 
              - model-docs/charts/index.md
              - submodel:
                  - model-docs/charts/submodel/index.md
          - model-docs/target.md
          - model-docs/dashboard.md
          - model-docs/default.md
          - model-docs/alert.md
  - Background:
      - Viewpoint: viewpoint.md
      - How It Works: how_it_works.md
