site_name: Visivo Docs

plugins:
  - search: {}
  - macros:
      module_name: mkdocs/src/main
  - spellcheck:
      backends: # the backends you want to use
        - symspellpy # as strings
        - codespell: # or nested configs
            dictionaries: [clear, rare]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/visivo-io/visivo
repo_name: visivo-io/visivo
theme:
  name: material
  features:
    - content.tabs.link
    #- navigation.tabs
    - navigation.indexes
    #- navigation.path
    - navigation.sections
    - content.tooltips
  logo: assets/favicon_io/android-chrome-192x192.png
  favicon: assets/favicon_io/favicon-32x32.png
  icon:
    annotation: material/arrow-right-circle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: visivo_light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: visivo_dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: "mkdocs"
site_dir: "mkdocs_build"

extra:
  analytics:
    provider: google
    property: G-50DF3C95TL

extra_css:
  - stylesheets/brand_colors.css

nav:
  - Getting Started: index.md
  - Topics:
      - Linting: topics/linting.md
      - Including: topics/including.md
      - Deployment: topics/deployments.md
    # - Use Cases: use_cases.md
    # - Tutorials: how_tos.md
  - Reference:
      - CLI: reference/cli.md
      - Configuration:
          - Traces: 
            - reference/configuration/traces/index.md
          #- Trace Properties:
            - '<b>Bar</b>': reference/configuration/traces/bar.md
            - BarPolar: reference/configuration/traces/barpolar.md
            - '<b>Box</b>': reference/configuration/traces/box.md
            - CandleStick: reference/configuration/traces/candlestick.md
            - Carpet: reference/configuration/traces/carpet.md
            - Choropleth: reference/configuration/traces/choropleth.md
            - ChoroplethMapBox: reference/configuration/traces/choroplethmapbox.md
            - Cone: reference/configuration/traces/cone.md
            - Contour: reference/configuration/traces/contour.md
            - ContourCarpet: reference/configuration/traces/contourcarpet.md
            - DensityMapBox: reference/configuration/traces/densitymapbox.md
            - '<b>Funnel</b>': reference/configuration/traces/funnel.md
            - FunnelArea: reference/configuration/traces/funnelarea.md
            - Heatmap: reference/configuration/traces/heatmap.md
            - Heatmapgl: reference/configuration/traces/heatmapgl.md
            - Histogram: reference/configuration/traces/histogram.md
            - Histogram2d: reference/configuration/traces/histogram2d.md
            - Histogram2dContour: reference/configuration/traces/histogram2dcontour.md
            - Icicle: reference/configuration/traces/icicle.md
            - Image: reference/configuration/traces/image.md
            - Indicator: reference/configuration/traces/indicator.md
            - IsoSurface: reference/configuration/traces/isosurface.md
            - Mesh3d: reference/configuration/traces/mesh3d.md
            - Ohlc: reference/configuration/traces/ohlc.md
            - Parcats: reference/configuration/traces/parcats.md
            - Parcoords: reference/configuration/traces/parcoords.md
            - '<b>Pie</b>': reference/configuration/traces/pie.md
            - Sankey: reference/configuration/traces/sankey.md
            - '<b>Scatter</b>': reference/configuration/traces/scatter.md
            - Scatter3d: reference/configuration/traces/scatter3d.md
            - ScatterCarpet: reference/configuration/traces/scattercarpet.md
            - ScatterGeo: reference/configuration/traces/scattergeo.md
            - ScatterGL: reference/configuration/traces/scattergl.md
            - ScatterMapBox: reference/configuration/traces/scattermapbox.md
            - ScatterPolar: reference/configuration/traces/scatterpolar.md
            - ScatterPolarGl: reference/configuration/traces/scatterpolargl.md
            - ScatterSmith: reference/configuration/traces/scattersmith.md
            - Scatterternary: reference/configuration/traces/scatterternary.md
            - Splom: reference/configuration/traces/splom.md
            - Streamtube: reference/configuration/traces/streamtube.md
            - Sunburst: reference/configuration/traces/sunburst.md
            - Surface: reference/configuration/traces/surface.md
            - '<b>Treemap</b>': reference/configuration/traces/treemap.md
            - Violin: reference/configuration/traces/violin.md
            - Volume: reference/configuration/traces/volume.md
            - '<b>Waterfall</b>': reference/configuration/traces/waterfall.md
          - Charts: 
              - reference/configuration/charts/index.md
              - submodel:
                  - reference/configuration/charts/submodel/index.md
          - reference/configuration/target.md
          - reference/configuration/dashboard.md
          - reference/configuration/default.md
          - reference/configuration/alert.md
  - Background:
      - Viewpoint: viewpoint.md
      - How It Works: how_it_works.md
