name: Deploy Docs to Github Pages

on:
  push:
    branches: [ "main", "tim/open-source" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install CLI Dependencies
        run: pip install poetry && poetry install --with dev && poetry run visivo
      
      - name: Build Mkdocs
        run: PYTHONPATH=$PWD poetry run mkdocs build 
      
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'mkdocs_build'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
