name: Deploy Docs to Github Pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x' 

      - name: Install CLI Dependencies
        run: cd cli && pip install poetry && poetry install --with dev && poetry run visivo && cd ..
      
      - name: Install CSS Dependencies
        run: cd cli && yarn install && cd ..

      - name: Build CSS 
        run: cd cli && npx tailwindcss -i ./mkdocs/stylesheets/input.css -o ./mkdocs/overrides/assets/css/home.css && cd ..
      
      - name: Deploy mkdocs to docs.visivo.io
        run: cd cli && PYTHONPATH=$PWD poetry run mkdocs build && PYTHONPATH=$PWD poetry run mkdocs gh-deploy --force
      
      

