name: Mint Migration

on: [push]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Install Mint CLI
        run: |
          curl -L https://github.com/rwx-research/mint-cli/releases/download/v0/mint-linux-x86_64 > mint
          chmod +x mint
          ./mint --version
      - name: Set Secrets
        run: |
          ./mint vaults set-secrets \
            CLI_UNIT_TESTING_SNOWFLAKE_PASSWORD="${{ secrets.CLI_UNIT_TESTING_SNOWFLAKE_PASSWORD }}" \
            CLI_UNIT_TESTING_SNOWFLAKE_USER="${{ secrets.CLI_UNIT_TESTING_SNOWFLAKE_USER }}" \
            NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            NETLIFY_SITE_ID="${{ secrets.NETLIFY_SITE_ID }}" \
            SNOWFLAKE_ACCOUNT="${{ secrets.SNOWFLAKE_ACCOUNT }}" \
            VISIVO_TOKEN="${{ secrets.VISIVO_TOKEN }}"
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
