name: Test

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: Gr1N/setup-poetry@v8 
      
      - name: Install Dependencies
        run: poetry install
      
      - name: Test CLI
        run: poetry run pytest 